### ISSUE TITLE
update favicon

### ISSUE THREAD

**Issue by mattkanwisher** [loomnetwork/blockscout#13]
<img width="123" alt="Screen Shot 2019-04-22 at 8 56 38 PM" src="https://user-images.githubusercontent.com/3032/56499418-3b14a880-6541-11e9-8fc9-69242e0a554d.png">

**Comment by eduardonunesp** [comment]
Updated: favicon, footer links and footer icons

![image](https://user-images.githubusercontent.com/582516/56547988-44a80b80-6555-11e9-915f-1abc6528c542.png)


![image](https://user-images.githubusercontent.com/582516/56547943-280bd380-6555-11e9-85d2-b79daeebe81f.png)
