### ISSUE TITLE
display address in loom format

### ISSUE THREAD

**Issue by lukezhangstudio** [loomnetwork/blockscout#18]
addresses should be displayed in loom format like
`loomf825EEB10F9cF76012FB155751B3A0437fc31442`
instead of
`0xf825EEB10F9cF76012FB155751B3A0437fc31442`

to prevent users from sending funds to incorrect places

**Comment by eduardonunesp** [comment]
We have a problem here, to change to `loom` prefix there's a problem to show the address, everywhere deep in the application the pattern is to show `0x`

**Comment by eduardonunesp** [comment]
I can change to show at least on the front end to show `loom` in the front of the address instead `0x`

**Comment by eduardonunesp** [comment]
K pushed to `master` maybe @bikashdas can deploy redeploy later

**Comment by bikashdas** [comment]
Deployed. Display address is in loom format now
![display-address](https://user-images.githubusercontent.com/10044695/57133187-a8d19780-6dbf-11e9-8f0f-13533f89965c.PNG)
