### ISSUE TITLE
search should accept eth address or loom address

### ISSUE THREAD

**Issue by lukezhangstudio** [loomnetwork/blockscout#20]
should use the mapping api to accept searches in the `eth:00000000000000000` notation and look up the corresponding loom address

ex: http://dev-account-explorer.dappchains.com/?account=eth%3A0x47609a5c1399274bf310a3910dede5ff5cead7ec

api: `http://account-explorer.dappchains.com/get_account/eth:0x47609a5c1399274bf310a3910dede5ff5cead7ec

**Comment by eduardonunesp** [comment]
Right now the blockscout indexes based on web3 api enabled by loomchain, to add a mapping will require to lookup on the api `http://account-explorer.dappchains.com/get_account/eth:0x47609a5c1399274bf310a3910dede5ff5cead7ec` for each new address. Is the issue to add a capability of search address with a prefix `eth:` or `loom:` or to show the mapping address on blockscout
