### ISSUE TITLE
Verify and test ERC721 support on the dappchain

### ISSUE THREAD

**Issue by mattkanwisher** [loomnetwork/blockscout#21]

**Comment by eduardonunesp** [comment]
There's an issue on compile and verify the solidity contract on the interface, there's open issue https://github.com/poanetwork/blockscout/issues/1884

**Comment by eduardonunesp** [comment]
Support also the names for the contracts appearing on the transactions 

![image](https://user-images.githubusercontent.com/582516/58114747-cfb90780-7bce-11e9-8fbe-dbe40d298a7c.png)


![image](https://user-images.githubusercontent.com/582516/58114765-d8114280-7bce-11e9-897e-6517eff61161.png)
