### ISSUE TITLE
Contract verifier doesn't seem to work correctly

### ISSUE THREAD

**Issue by andreipope** [loomnetwork/blockscout#39]
A user reported that the contract verification doesn’t work on Plasma. Managed to reproduce the issue on extdev and I’m wondering… are we using a different EVM version that’s not in the list?
P.S.: tried all EVM versions.
<img width="1208" alt="Screenshot 2019-07-16 08 36 52" src="https://user-images.githubusercontent.com/32929697/61272637-e41d1900-a7a7-11e9-9d9d-e566a9f28cfd.png">

User report:
<img width="562" alt="Screenshot 2019-07-16 08 59 10" src="https://user-images.githubusercontent.com/32929697/61272696-044cd800-a7a8-11e9-905e-72128d63bab6.png">

**Comment by andreipope** [comment]
Was able to reproduce the problem using this contract:

https://github.com/loomnetwork/eth-signing-demo/blob/master/truffle/contracts/SimpleStore.sol.

https://github.com/loomnetwork/eth-signing-demo/blob/master/truffle/build/contracts/SimpleStore.json

**Comment by eduardonunesp** [comment]
Can't reproduce, I think we need more information

http://extdev-blockexplorer.dappchains.com/address/0x4de44226c769188193931c70863258e89c585811/contracts
