### ISSUE TITLE
Place holder text getting cut on search bar

### ISSUE THREAD

**Issue by Kanavs27** [loomnetwork/blockscout#46]
Go to http://plasma-blockexplorer.dappchains.com/

![image](https://user-images.githubusercontent.com/44959753/62282333-fb792900-b46c-11e9-8e9f-18f6ee688175.png)

**Comment by eduardonunesp** [comment]
On new version  on asia1 it depends on the size of the screen, bigger than 1440 width it will show entire, otherwise putting the mouse over the text are will show the entire text

**Comment by yuneeksehgal** [comment]
This is looking better

![image](https://user-images.githubusercontent.com/23660413/65014076-0879ab00-d93b-11e9-98fa-fec61682adde.png)
