### ISSUE TITLE
UTF-8 showing special symbols on transaction details page

### ISSUE THREAD

**Issue by Kanavs27** [loomnetwork/blockscout#52]
- Go to http://plasma-blockexplorer.dappchains.com/tx/0xbfe68fecaa69351e4a4d61fbd046e3eb6d82dab81030d1bb56020dbccdf0b920/internal_transactions

- Select UTF-8 from drop-down

![image](https://user-images.githubusercontent.com/44959753/62290376-df7e8300-b47e-11e9-8100-453051a80d22.png)

**Comment by eduardonunesp** [comment]
This is not an issue, is just a normal behavior when users try to display non supported chars on the browser it happens also with Etherscan contracts, many users will not care or try to display binary to utf-8
