### ISSUE TITLE
Mobile: Tooltip getting overlap on QR Code pop up using android mobile

### ISSUE THREAD

**Issue by Kanavs27** [loomnetwork/blockscout#54]
- Go to http://plasma-blockexplorer.dappchains.com/address/0xe9837e455f09300e98f5ac59d862da781da594e7/transactions

- Video:
https://slack-files.com/T7AB1S3LN-FM1SSCBC7-99f079579b

**Comment by eduardonunesp** [comment]
Not an issue the user can touch on the tooltip again and it will close
