### ISSUE TITLE
Mobile: Tool tip remain on the screen and do not go away

### ISSUE THREAD

**Issue by Kanavs27** [loomnetwork/blockscout#55]
- Go to http://plasma-blockexplorer.dappchains.com/tx/0x4f3d09e51939903ef5dc095cf1289cda73e12dbd34e1639802ca3bccb5b6d596/internal_transactions

- Click on copy address button

- Video
https://slack-files.com/T7AB1S3LN-FLNKF8WF5-3f2ba7b44b

**Comment by eduardonunesp** [comment]
It's ok, it's a lower priority, I'll not consider an issue because isn't something that blocks the user to continue use the application
