### ISSUE TITLE
Mobile: UI issue with balance graph on address details page

### ISSUE THREAD

**Issue by Kanavs27** [loomnetwork/blockscout#57]
- Go to http://plasma-blockexplorer.dappchains.com/address/0xc5d1847a03da59407f27f8fe7981d240bff2dfd3/coin_balances

- Try to open above URL on android mobile

![2019-08-02_17h40_38](https://user-images.githubusercontent.com/44959753/62369393-191dbf80-b54d-11e9-9b2d-24e89cd94ca7.png)

**Comment by eduardonunesp** [comment]
This page isn't used anymore
