### ISSUE TITLE
Token list drop down showing duplicate entries for BNB on address details page

### ISSUE THREAD

**Issue by Kanavs27** [loomnetwork/blockscout#59]
- Go to http://plasma-blockexplorer.dappchains.com/address/0x3f0a8664cca9faa63298a7a6b8c0ac16001957c8/transactions

- Click token list dropdown under balance section

![2019-08-05_19h23_48](https://user-images.githubusercontent.com/44959753/62470015-145c4400-b7b7-11e9-974d-670a80ea1d71.png)

**Comment by eduardonunesp** [comment]
Hey, thanks for the report, actually those names `BNBToken` are duplicated they are different contracts with the same name, names are ok to duplicate but the addresses aren't

**Comment by Kanavs27** [comment]
Hey @eduardonunesp Thanks for the update :smiley:
