### ISSUE TITLE
Incorrect binance token value showing for my loom address

### ISSUE THREAD

**Issue by Kanavs27** [loomnetwork/blockscout#61]
- Go to http://plasma-blockexplorer.dappchains.com/address/0x4a5fc5ebb4301c320264fe50413802d437181be6/transactions

- Click token list dropdown under balance section

![2019-08-06_13h27_45](https://user-images.githubusercontent.com/44959753/62521954-4a003c00-b84e-11e9-9bad-c5db5d36cd61.png)

**Comment by Kanavs27** [comment]
- Go to http://plasma-blockexplorer.dappchains.com/address/0x4a5fc5ebb4301c320264fe50413802d437181be6/transactions

- Click token list dropdown under balance section

![2019-08-06_13h27_45](https://user-images.githubusercontent.com/44959753/62521954-4a003c00-b84e-11e9-9bad-c5db5d36cd61.png)

**Comment by eduardonunesp** [comment]
Hi @Kanavs27 could you please add why it's incorrect, and what is the expected the value ?

**Comment by Kanavs27** [comment]
@eduardonunesp I am not sure for 100,000,000,000,000,000 amount is valid for listed token BNTK

This is my loom address
loom4A5fc5eBb4301c320264fE50413802D437181BE6

**Comment by eduardonunesp** [comment]
Actually there's nothing wrong one `100,000,000,000,000,000` is the amount that your address holds, the other is the values that the contract holds
