### ISSUE TITLE
Copy address button missing on block details page

### ISSUE THREAD

**Issue by Kanavs27** [loomnetwork/blockscout#62]
- Go to http://plasma-blockexplorer.dappchains.com/blocks/6277198/transactions

![2019-08-06_13h31_57](https://user-images.githubusercontent.com/44959753/62522228-e0ccf880-b84e-11e9-95bf-ffdc97e78070.png)

**Comment by eduardonunesp** [comment]
The copy button is only available on the white card on the left, according to the design principles the green block on the right doesn't need a copy button

**Comment by Kanavs27** [comment]
Fixed on asia1
